/*
 * Atypical Calling Convention Module
 *
 * Based on CoreCLR source analysis: Go's asmcgocall creates "atypical calling
 * conventions" and "non-standard function prologues/epilogues" that stress
 * IsIPInEpilog/IsIPInProlog analysis to consume 16-24KB per call chain.
 *
 * This module replicates those exact characteristics.
 */

#define _GNU_SOURCE
#include <stdint.h>
#include <string.h>
#include <setjmp.h>

// Forward declarations for atypical assembly functions
extern void atypical_prologue_function_1(void* context, uintptr_t param1, uintptr_t param2, uintptr_t param3);
extern void atypical_prologue_function_2(void* context, uintptr_t param1, uintptr_t param2, uintptr_t param3);
extern void atypical_prologue_function_3(void* context, uintptr_t param1, uintptr_t param2, uintptr_t param3);
extern int complex_register_manipulation_chain(void* ctx, int depth, uintptr_t data);
extern void stack_frame_confusion_pattern(void* ctx, uintptr_t base);

/*
 * Assembly functions with atypical calling conventions
 * These replicate the "non-standard prologues/epilogues" that stress
 * CoreCLR's IP boundary analysis to 16-24KB per call chain
 */
__asm__(
"   .text\n"
"   .globl atypical_prologue_function_1\n"
"atypical_prologue_function_1:\n"
"   # Atypical prologue - non-standard register usage like Go's asmcgocall\n"
"   pushq %rbp\n"
"   movq  %rsp, %rbp\n"
"   # Unusual register preservation pattern\n"
"   pushq %rax\n"
"   pushq %rcx\n"
"   pushq %rdx\n"
"   pushq %rbx\n"
"   pushq %rsi\n"
"   pushq %rdi\n"
"   pushq %r8\n"
"   pushq %r9\n"
"   pushq %r10\n"
"   pushq %r11\n"
"   pushq %r12\n"
"   pushq %r13\n"
"   pushq %r14\n"
"   pushq %r15\n"
"   # Create large stack frame that confuses analysis\n"
"   subq  $2048, %rsp\n"
"   \n"
"   # Store parameters in non-standard locations\n"
"   movq  %rdi, -8(%rbp)     # context\n"
"   movq  %rsi, -16(%rbp)    # param1  \n"
"   movq  %rdx, -24(%rbp)    # param2\n"
"   movq  %rcx, -32(%rbp)    # param3\n"
"   \n"
"   # Complex register manipulation that stresses unwinding\n"
"   movq  %rsi, %r12         # param1 → r12\n"
"   movq  %rdx, %r13         # param2 → r13\n"
"   movq  %rcx, %r14         # param3 → r14\n"
"   \n"
"   # Create complex call pattern with modified calling convention\n"
"   movq  %rdi, %rax         # context in RAX (atypical)\n"
"   movq  %r12, %rbx         # param1 in RBX (atypical)\n"
"   movq  %r13, %rcx         # param2 in RCX\n"
"   movq  %r14, %rdx         # param3 in RDX  \n"
"   callq atypical_prologue_function_2\n"
"   \n"
"   # More register shuffling to confuse analysis\n"
"   movq  %rax, %r15         # Result in non-standard register\n"
"   \n"
"   # Call with different parameter arrangement\n"
"   movq  -8(%rbp), %rdi     # Reload context\n"
"   movq  %r15, %rsi         # Previous result as param1\n"
"   movq  %r13, %rdx         # param2 unchanged\n"
"   movq  %r14, %rcx         # param3 unchanged\n"
"   callq atypical_prologue_function_3\n"
"   \n"
"   # Atypical epilogue - non-standard cleanup\n"
"   addq  $2048, %rsp\n"
"   popq  %r15\n"
"   popq  %r14\n"
"   popq  %r13\n"
"   popq  %r12\n"
"   popq  %r11\n"
"   popq  %r10\n"
"   popq  %r9\n"
"   popq  %r8\n"
"   popq  %rdi\n"
"   popq  %rsi\n"
"   popq  %rbx\n"
"   popq  %rdx\n"
"   popq  %rcx\n"
"   popq  %rax\n"
"   leave\n"
"   ret\n"
"\n"
"   .globl atypical_prologue_function_2\n"
"atypical_prologue_function_2:\n"
"   # Different atypical prologue pattern\n"
"   pushq %rbp\n"
"   pushq %rbx            # Non-standard order\n"
"   pushq %r12\n"
"   pushq %r13\n"
"   movq  %rsp, %rbp\n"   /* rbp setup after pushes (atypical) */
"   \n"
"   # Massive stack allocation to stress unwinding\n"
"   subq  $4096, %rsp\n"
"   \n"
"   # Parameters passed in atypical registers from caller\n"
"   movq  %rax, %r12      # context from RAX\n"
"   movq  %rbx, %r13      # param1 from RBX\n"
"   # rcx, rdx still have param2, param3\n"
"   \n"
"   # Create complex frame relationships\n"
"   movq  %rsp, -8(%rbp)  # Store current SP in unusual location\n"
"   movq  %r12, -16(%rbp) # context\n"
"   movq  %r13, -24(%rbp) # param1\n"
"   movq  %rcx, -32(%rbp) # param2\n"
"   movq  %rdx, -40(%rbp) # param3\n"
"   \n"
"   # Call C function with complex parameters to amplify analysis\n"
"   movq  %r12, %rdi      # context\n"
"   movq  $25, %rsi       # depth\n"
"   movq  %r13, %rdx      # data\n"
"   callq complex_register_manipulation_chain\n"
"   \n"
"   # Store result in atypical location\n"
"   movq  %rax, -48(%rbp)\n"
"   \n"
"   # Chain to next function with modified convention\n"
"   movq  %r12, %rax      # context in RAX again\n"
"   movq  -48(%rbp), %rbx # result in RBX\n"
"   movq  %rcx, %rcx      # param2 unchanged\n"
"   movq  %rdx, %rdx      # param3 unchanged\n"
"   callq atypical_prologue_function_3\n"
"   \n"
"   # Atypical cleanup\n"
"   addq  $4096, %rsp\n"
"   popq  %r13\n"
"   popq  %r12\n"
"   popq  %rbx\n"
"   leave\n"
"   ret\n"
"\n"
"   .globl atypical_prologue_function_3\n"
"atypical_prologue_function_3:\n"
"   # Most complex atypical pattern\n"
"   pushq %rbp\n"
"   # Save registers in non-standard pattern\n"
"   pushq %rax\n"
"   pushq %rbx\n"
"   pushq %rcx\n"
"   pushq %rdx\n"
"   pushq %rsi\n"
"   pushq %rdi\n"
"   movq  %rsp, %rbp\n"
"   \n"
"   # Extreme stack allocation\n"
"   subq  $8192, %rsp     # 8KB frame\n"
"   \n"
"   # Complex parameter handling\n"
"   movq  %rax, -8(%rbp)  # context from RAX\n"
"   movq  %rbx, -16(%rbp) # param from RBX\n"
"   # rcx, rdx still standard\n"
"   \n"
"   # Create multiple stack frame confusion patterns\n"
"   movq  -8(%rbp), %rdi  # context\n"
"   movq  -16(%rbp), %rsi # param as base\n"
"   callq stack_frame_confusion_pattern\n"
"   \n"
"   # More confusion patterns\n"
"   movq  -8(%rbp), %rdi  # context\n"
"   movq  $50, %rsi       # large depth\n"
"   movq  %rcx, %rdx      # param2 as data\n"
"   callq complex_register_manipulation_chain\n"
"   \n"
"   # Final confusion call\n"
"   movq  -8(%rbp), %rdi  # context\n"
"   movq  %rdx, %rsi      # param3 as base\n"
"   callq stack_frame_confusion_pattern\n"
"   \n"
"   # Complex epilogue\n"
"   addq  $8192, %rsp\n"
"   popq  %rdi\n"
"   popq  %rsi\n"
"   popq  %rdx\n"
"   popq  %rcx\n"
"   popq  %rbx\n"
"   popq  %rax\n"
"   leave\n"
"   ret\n"
"\n"
"   .globl complex_register_manipulation_chain\n"
"complex_register_manipulation_chain:\n"
"   # Assembly portion of complex manipulation\n"
"   pushq %rbp\n"
"   movq  %rsp, %rbp\n"
"   # Save all registers in complex pattern\n"
"   subq  $256, %rsp      # Large local area\n"
"   \n"
"   # Store parameters in complex locations\n"
"   movq  %rdi, -8(%rbp)  # ctx\n"
"   movq  %rsi, -16(%rbp) # depth\n"
"   movq  %rdx, -24(%rbp) # data\n"
"   \n"
"   # Manipulate parameters before C call\n"
"   movq  %rsi, %rax      # depth\n"
"   imulq $17, %rax       # depth * 17\n"
"   addq  %rdx, %rax      # + data\n"
"   movq  %rax, -32(%rbp) # store modified\n"
"   \n"
"   # Call C function with modified parameters\n"
"   movq  %rdi, %rdi      # ctx unchanged\n"
"   movq  %rsi, %rsi      # depth unchanged\n"
"   movq  -32(%rbp), %rdx # modified data\n"
"   callq complex_register_manipulation_chain_c\n"
"   \n"
"   # Post-process result\n"
"   movq  %rax, %rcx\n"
"   movq  -24(%rbp), %rdx # original data\n"
"   xorq  %rdx, %rcx      # result XOR original\n"
"   movq  %rcx, %rax      # final result\n"
"   \n"
"   addq  $256, %rsp\n"
"   leave\n"
"   ret\n"
"\n"
"   .globl stack_frame_confusion_pattern\n"
"stack_frame_confusion_pattern:\n"
"   # Create extremely confusing stack frame patterns\n"
"   pushq %rbp\n"
"   movq  %rsp, %rbp\n"
"   subq  $1024, %rsp\n"
"   \n"
"   # Store parameters in scattered locations\n"
"   movq  %rdi, -8(%rbp)   # ctx\n"
"   movq  %rsi, -256(%rbp) # base (far from normal)\n"
"   \n"
"   # Create fake frame pointers\n"
"   movq  %rbp, -16(%rbp)  # Self-reference\n"
"   leaq  -512(%rbp), %rax\n"
"   movq  %rax, -512(%rbp) # Fake frame in middle\n"
"   \n"
"   # Call C function\n"
"   movq  %rdi, %rdi       # ctx\n"
"   movq  %rsi, %rsi       # base\n"
"   callq stack_frame_confusion_pattern_c\n"
"   \n"
"   addq  $1024, %rsp\n"
"   leave\n"
"   ret\n"
);